# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/sum_0_120_240_360/sum_0_120_240_360.xci
# IP: The module: 'sum_0_120_240_360' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.gen/sources_1/ip/sum_0_120_240_360/sum_0_120_240_360_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sum_0_120_240_360'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/sum_0_120_240_360/sum_0_120_240_360.xci
# IP: The module: 'sum_0_120_240_360' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.gen/sources_1/ip/sum_0_120_240_360/sum_0_120_240_360_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sum_0_120_240_360'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
