# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/bd/design_1/ip/design_1_vp_0_0/design_1_vp_0_0.xci
# IP: The module: 'design_1_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/mnozarka255/mnozarka255.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mnozarka255 || ORIG_REF_NAME==mnozarka255} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/sum_0_120_240_360/sum_0_120_240_360.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sum_0_120_240_360 || ORIG_REF_NAME==sum_0_120_240_360} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/color_difference/color_difference.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_difference || ORIG_REF_NAME==color_difference} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/adder/adder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/multiply/multiply.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/DivC/DivC.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DivC || ORIG_REF_NAME==DivC} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/div_S/div_S.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_S || ORIG_REF_NAME==div_S} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/dzielnik_na_360/dzielnik_na_360.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dzielnik_na_360 || ORIG_REF_NAME==dzielnik_na_360} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/dzielnik_na_255/dzielnik_na_255.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dzielnik_na_255 || ORIG_REF_NAME==dzielnik_na_255} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# XDC: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.gen/sources_1/bd/design_1/ip/design_1_vp_0_0/design_1_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_vp_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/bd/design_1/ip/design_1_vp_0_0/design_1_vp_0_0.xci
# IP: The module: 'design_1_vp_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/mnozarka255/mnozarka255.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mnozarka255 || ORIG_REF_NAME==mnozarka255} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/sum_0_120_240_360/sum_0_120_240_360.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sum_0_120_240_360 || ORIG_REF_NAME==sum_0_120_240_360} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/color_difference/color_difference.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_difference || ORIG_REF_NAME==color_difference} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/adder/adder.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/multiply/multiply.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/DivC/DivC.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DivC || ORIG_REF_NAME==DivC} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/div_S/div_S.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_S || ORIG_REF_NAME==div_S} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/dzielnik_na_360/dzielnik_na_360.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dzielnik_na_360 || ORIG_REF_NAME==dzielnik_na_360} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/dzielnik_na_255/dzielnik_na_255.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dzielnik_na_255 || ORIG_REF_NAME==dzielnik_na_255} -quiet] -quiet

# IP: C:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/divider_32_20_0/divider_32_20_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# XDC: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.gen/sources_1/bd/design_1/ip/design_1_vp_0_0/design_1_vp_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_vp_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
