# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/color_difference/color_difference.xci
# IP: The module: 'color_difference' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.gen/sources_1/ip/color_difference/color_difference_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'color_difference'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/color_difference/color_difference.xci
# IP: The module: 'color_difference' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.gen/sources_1/ip/color_difference/color_difference_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'color_difference'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
