# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/SDwUP/base.xdc

# IP: ip/DivC/DivC.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DivC || ORIG_REF_NAME==DivC} -quiet] -quiet

# IP: ip/div_S/div_S.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_S || ORIG_REF_NAME==div_S} -quiet] -quiet

# IP: ip/dzielnik_na_360/dzielnik_na_360.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dzielnik_na_360 || ORIG_REF_NAME==dzielnik_na_360} -quiet] -quiet

# IP: ip/dzielnik_na_255/dzielnik_na_255.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dzielnik_na_255 || ORIG_REF_NAME==dzielnik_na_255} -quiet] -quiet

# IP: ip/divider_32_20_0/divider_32_20_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_1/design_1_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_1 || ORIG_REF_NAME==design_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_1 || ORIG_REF_NAME==design_1_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dvi2rgb_0_2/design_1_dvi2rgb_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dvi2rgb_0_2 || ORIG_REF_NAME==design_1_dvi2rgb_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rgb2dvi_0_0/design_1_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rgb2dvi_0_0 || ORIG_REF_NAME==design_1_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0/design_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_vp_0_0/design_1_vp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_vp_0_0 || ORIG_REF_NAME==design_1_vp_0_0} -quiet] -quiet

# IP: ip/mnozarka255/mnozarka255.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mnozarka255 || ORIG_REF_NAME==mnozarka255} -quiet] -quiet

# IP: ip/mult_gen_1/mult_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: ip/sum_0_120_240_360/sum_0_120_240_360.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sum_0_120_240_360 || ORIG_REF_NAME==sum_0_120_240_360} -quiet] -quiet

# IP: ip/color_difference/color_difference.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_difference || ORIG_REF_NAME==color_difference} -quiet] -quiet

# IP: ip/adder/adder.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==adder || ORIG_REF_NAME==adder} -quiet] -quiet

# IP: ip/multiply/multiply.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==multiply || ORIG_REF_NAME==multiply} -quiet] -quiet

# IP: ip/DivC/DivC.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DivC || ORIG_REF_NAME==DivC} -quiet] -quiet

# IP: ip/div_S/div_S.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_S || ORIG_REF_NAME==div_S} -quiet] -quiet

# IP: ip/dzielnik_na_360/dzielnik_na_360.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dzielnik_na_360 || ORIG_REF_NAME==dzielnik_na_360} -quiet] -quiet

# IP: ip/dzielnik_na_255/dzielnik_na_255.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dzielnik_na_255 || ORIG_REF_NAME==dzielnik_na_255} -quiet] -quiet

# IP: ip/divider_32_20_0/divider_32_20_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==divider_32_20_0 || ORIG_REF_NAME==divider_32_20_0} -quiet] -quiet

# XDC: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.gen/sources_1/bd/design_1/design_1_ooc.xdc
