# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/divider/divider.xci
# IP: The module: 'divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.gen/sources_1/ip/divider/src/mult_32_20_lm/mult_32_20_lm.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet

# IP: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.srcs/sources_1/ip/divider/divider.xci
# IP: The module: 'divider' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/bjsmn1/Desktop/Uczelnia/SDwUP/Projekt/tor_wizyjny/tor_wizyjny.gen/sources_1/ip/divider/src/mult_32_20_lm/mult_32_20_lm.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_32_20_lm || ORIG_REF_NAME==mult_32_20_lm} -quiet] -quiet
